services:
  mysql:
    image: mysql:8.4
    container_name: hiresense-mysql
    environment:
      MYSQL_DATABASE: hiresense
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: hiresense
      MYSQL_PASSWORD: hiresense
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
